blank_issues_enabled: false
contact_links:
 - name: GitHub Community
   url: https://github.com/svitejs/vite-plugin-qrcode/discussions
   about: Please ask and answer questions here.
#  - name: Discord
#    url: https://discord.gg/nzgMZJD
#    about: If you want to chat, join our discord.
